[versions]
agp = "8.13.0"
# This project builds with agp 8.12.2 but fails to build with agp 8.13.0
#agp = "8.12.2"
kotlin = "2.2.10"
coreKtx = "1.17.0"
fragmentKtx = "1.8.9"
navigationFragment = "2.9.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

